# Generated by Django 3.1.5 on 2021-01-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('user_profile', '0003_auto_20210114_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollow',
            name='followed_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='UserFollowed_by', to='authentication.NewUsers'),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='UserFollowing', to='authentication.NewUsers'),
        ),
    ]
