# Generated by Django 3.1.5 on 2021-01-17 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('user_profile', '0013_auto_20210115_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ManyToManyField(to='authentication.NewUsers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to='authentication.newusers')),
            ],
        ),
    ]
