# Generated by Django 3.1.5 on 2021-01-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('user_profile', '0014_postbookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbookmark',
            name='post',
            field=models.ManyToManyField(blank=True, to='authentication.NewUsers'),
        ),
    ]
