# Generated by Django 3.1.5 on 2021-01-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPost', '0006_auto_20210116_0426'),
        ('user_profile', '0015_auto_20210116_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbookmark',
            name='post',
            field=models.ManyToManyField(blank=True, to='UserPost.Post'),
        ),
    ]
