# Generated by Django 3.1.5 on 2021-01-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0018_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
