# Generated by Django 3.1.5 on 2021-03-23 16:01

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0019_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='cover_picture',
            field=models.ImageField(default='CoverPic/meWithNature.jpg', upload_to=user_profile.models.uploadCover_to),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='gander',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='occupations',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='relationship_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
