// Authentications
export const AUTH_START   = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT  = 'AUTH_LOGOUT'
export const AUTH_REGISTRATION  = 'AUTH_REGISTRATION'
export const CAHNGE_PASSWORD = 'CHANGE_PASSWORD'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const AUTH_LOGIN_FAIL    = 'AUTH_LOGIN_FAIL'
export const AUTH_REGISTRATION_FAIL    = 'AUTH_REGISTRATION_FAIL'
export const VERIFY_JWT_TOKEN = 'VERIFY_JWT_TOKEN'
export const PASSWORD_CHANGE_FILED = 'PASSWORD_CHANGE_FILED'
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS'
export const REMOVE_PASSWORD_CHANGE_SUCCESS = 'REMOVE_PASSWORD_CHANGE_SUCCESS'
export const RESET_EMAIL_CHANGED_SUCCESS = 'RESET_EMAIL_CHANGED_SUCCESS'
export const REMOVE_RESET_EMAIL_CHANGED_SUCCESS = 'REMOVE_RESET_EMAIL_CHANGED_SUCCESS'
export const RESET_EMAIL_CHANGED_FAILED= 'RESET_EMAIL_CHANGED_FAILED'
export const RESET_PASSSWORD_SUCCESS= 'RESET_PASSSWORD_SUCCESS'
export const RESET_PASSSWORD_FAILED= 'RESET_PASSSWORD_FAILED'
export const REMOVE_RESET_PASSSWORD_SUCCESS= 'REMOVE_RESET_PASSSWORD_SUCCESS'




// User profile 

export const USER_PROFILE_UPDATE_SUCCESS   = 'USER_PROFILE_UPDATE_SUCCESS'
export const REMOVE_USER_PROFILE_UPDATE_SUCCESS   = 'REMOVE_USER_PROFILE_UPDATE_SUCCESS'
export const USER_PROFILE_UPDATE_FAIL   = 'USER_PROFILE_UPDATE_FAIL'
export const LOGGED_IN_USER_INFO   = 'lOGGED_IN_USER_INFO'
export const RECOMENDED_USER   = 'RECOMENDED_USER'
export const MUTUAL_FRIEND   = 'MUTUAL_FRIEND'
export const REMOVE_MUTUAL_FRIEND = 'REMOVE_MUTUAL_FRIEND'

// utils
export const POST_LIKED_USER = 'POST_LIKED_USER'
export const REMOVE_POST_LIKED_USER = 'REMOVE_POST_LIKED_USER'
export const POST_SHARD_USER = 'POST_SHARE_USER'
export const REMOVE_POST_SHARD_USER = 'REMOVE_POST_SHARE_USER'
export const NOTIFICATION_COUNT = 'NOTIFICATION_COUNT'
export const NOTIFICATION_LIST = 'NOTIFICATION_LIST'
export const REMOVE_NOTIFICATION_LIST = 'REMOVE_NOTIFICATION_LIST'


// CRUD post

export const  GET_POST_START = 'GET_POST_START'
export const GET_POST_SUCCESS   = 'GET_POST_SUCCESS'
export const SHARE_POST_SUCCESS   = 'SHARE_POST_SUCCESS'


// get single post
export const GET_SINGLE_POST = 'GET_SINGLE_POST'

// User won post 

export const GET_USER_WON_POST_SUCCESS   = 'GET_USER_WON_POST_SUCCESS'
export const USER_PFORILE = 'USER_PFORILE'

// following and follower
export const GET_FOLLWING_USER = 'GET_FOLLWING_USER'
export const GET_FOLLWER_USER = 'GET_FOLLWER_USER'

// search user
export const SEARCH_USER_LIST = 'SEARCH_USER_LIST'