// Authentications
export const AUTH_START   = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT  = 'AUTH_LOGOUT'
export const AUTH_REGISTRATION  = 'AUTH_REGISTRATION'
export const CAHNGE_PASSWORD = 'CHANGE_PASSWORD'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const AUTH_LOGIN_FAIL    = 'AUTH_LOGIN_FAIL'
export const AUTH_REGISTRATION_FAIL    = 'AUTH_REGISTRATION_FAIL'
export const VERIFY_JWT_TOKEN    = 'VERIFY_JWT_TOKEN'

// User profile 

export const LOGGED_IN_USER_INFO   = 'lOGGED_IN_USER_INFO'

// CRUD post

export const  GET_POST_START = 'GET_POST_START'
export const GET_POST_SUCCESS   = 'GET_POST_SUCCESS'
export const SHARE_POST_SUCCESS   = 'SHARE_POST_SUCCESS'

