// Authentications
export const AUTH_START   = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT  = 'AUTH_LOGOUT'
export const AUTH_REGISTRATION  = 'AUTH_REGISTRATION'
export const CAHNGE_PASSWORD = 'CHANGE_PASSWORD'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const AUTH_LOGIN_FAIL    = 'AUTH_LOGIN_FAIL'
export const AUTH_REGISTRATION_FAIL    = 'AUTH_REGISTRATION_FAIL'
export const VERIFY_JWT_TOKEN    = 'VERIFY_JWT_TOKEN'

// User profile 

export const LOGGED_IN_USER_INFO   = 'lOGGED_IN_USER_INFO'
export const RECOMENDED_USER   = 'RECOMENDED_USER'
export const MUTUAL_FRIEND   = 'MUTUAL_FRIEND'
export const REMOVE_MUTUAL_FRIEND = 'REMOVE_MUTUAL_FRIEND'

// utils
export const POST_LIKED_USER = 'POST_LIKED_USER'
export const REMOVE_POST_LIKED_USER = 'REMOVE_POST_LIKED_USER'
export const POST_SHARD_USER = 'POST_SHARE_USER'
export const REMOVE_POST_SHARD_USER = 'REMOVE_POST_SHARE_USER'
export const NOTIFICATION_COUNT = 'NOTIFICATION_COUNT'
export const NOTIFICATION_LIST = 'NOTIFICATION_LIST'
export const REMOVE_NOTIFICATION_LIST = 'REMOVE_NOTIFICATION_LIST'


// CRUD post

export const  GET_POST_START = 'GET_POST_START'
export const GET_POST_SUCCESS   = 'GET_POST_SUCCESS'
export const SHARE_POST_SUCCESS   = 'SHARE_POST_SUCCESS'

// User won post 

export const GET_USER_WON_POST_SUCCESS   = 'GET_USER_WON_POST_SUCCESS'
export const USER_PFORILE = 'USER_PFORILE'

// following and follower
export const GET_FOLLWING_USER = 'GET_FOLLWING_USER'
export const GET_FOLLWER_USER = 'GET_FOLLWER_USER'