# Generated by Django 3.1.5 on 2021-01-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('UserPost', '0002_auto_20210115_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to='authentication.NewUsers'),
        ),
    ]
