# Generated by Django 3.1.5 on 2021-03-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPost', '0009_userpost_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='privacy',
            field=models.CharField(blank=True, choices=[('public', 'public'), ('friends', 'friends'), ('onlyme', 'onlyme')], default='friends', max_length=20, null=True),
        ),
    ]
