# Generated by Django 3.1.5 on 2021-03-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('UserPost', '0010_auto_20210308_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='shared_user',
            field=models.ManyToManyField(blank=True, related_name='shared_user', to='authentication.NewUsers'),
        ),
    ]
