# Generated by Django 3.1.5 on 2021-01-20 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserPost', '0008_auto_20210119_0307'),
        ('notification', '0004_auto_20210120_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postNotification', to='UserPost.userpost'),
        ),
    ]
